// Generated by CIRCT firtool-1.139.0
module DecoupledGcd(
  input         clock,
                reset,
  output        input_ready,
  input         input_valid,
  input  [15:0] input_bits_value1,
                input_bits_value2,
  input         output_ready,
  output        output_valid,
  output [15:0] output_bits_value1,
                output_bits_value2,
                output_bits_gcd
);

  reg  [15:0] xInitial;
  reg  [15:0] yInitial;
  reg  [15:0] x;
  reg  [15:0] y;
  reg         busy;
  reg         resultValid;
  wire        _GEN = x == 16'h0;
  always @(posedge clock) begin
    if (busy | ~input_valid) begin
    end
    else begin
      xInitial <= input_bits_value1;
      yInitial <= input_bits_value2;
    end
    if (busy) begin
      if (x > y)
        x <= x - y;
      else
        y <= y - x;
    end
    else if (input_valid) begin
      x <= input_bits_value1;
      y <= input_bits_value2;
    end
    if (reset) begin
      busy <= 1'h0;
      resultValid <= 1'h0;
    end
    else begin
      automatic logic _GEN_0;
      automatic logic _GEN_1;
      _GEN_0 = _GEN | y == 16'h0;
      _GEN_1 = output_ready & resultValid;
      if (busy)
        busy <= ~(_GEN_0 & _GEN_1);
      else
        busy <= input_valid;
      if (busy & _GEN_0)
        resultValid <= ~_GEN_1;
    end
  end // always @(posedge)
  assign input_ready = ~busy & input_valid | ~busy;
  assign output_valid = resultValid;
  assign output_bits_value1 = xInitial;
  assign output_bits_value2 = yInitial;
  assign output_bits_gcd = _GEN ? y : x;
endmodule

