// Generated by CIRCT firtool-1.139.0
module flowingled(
  input         clock,
                reset,
  output [15:0] io_led
);

  reg [31:0] counterreg;
  reg [15:0] ledreg;
  always @(posedge clock) begin
    if (reset) begin
      counterreg <= 32'h0;
      ledreg <= 16'h1;
    end
    else begin
      automatic logic _GEN = counterreg == 32'h26259F;
      counterreg <= _GEN ? 32'h0 : counterreg + 32'h1;
      if (_GEN)
        ledreg <= {ledreg[14:0], ledreg[15]};
    end
  end // always @(posedge)
  assign io_led = ledreg;
endmodule

